INSERT INTO user() 
VALUES()
INSERT INTO user() 
VALUES()
INSERT INTO user() 
VALUES()
INSERT INTO user() 
VALUES()
INSERT INTO user() 
VALUES()

INSERT INTO company() 
VALUES()
INSERT INTO company() 
VALUES()
INSERT INTO company() 
VALUES()
INSERT INTO company() 
VALUES()
INSERT INTO company() 
VALUES()

INSERT INTO product() 
VALUES()
INSERT INTO product() 
VALUES()
INSERT INTO product() 
VALUES()
INSERT INTO product() 
VALUES()
INSERT INTO product() 
VALUES()

INSERT INTO cart() 
VALUES()
INSERT INTO cart() 
VALUES()
INSERT INTO cart() 
VALUES()
INSERT INTO cart() 
VALUES()
INSERT INTO cart() 
VALUES()

INSERT INTO cart_and_product() 
VALUES()
INSERT INTO cart_and_product() 
VALUES()
INSERT INTO cart_and_product() 
VALUES()
INSERT INTO cart_and_product() 
VALUES()
INSERT INTO cart_and_product() 
VALUES()